# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movies.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmovies.proto\x12\x06movies\"\x86\x02\n\x05Movie\x12\x0b\n\x03_id\x18\x01 \x01(\t\x12\x0c\n\x04plot\x18\x02 \x01(\t\x12\x0e\n\x06genres\x18\x03 \x03(\t\x12\x0f\n\x07runtime\x18\x04 \x01(\x05\x12\x0c\n\x04\x63\x61st\x18\x05 \x03(\t\x12\x1a\n\x12num_mflix_comments\x18\x06 \x01(\x05\x12\r\n\x05title\x18\x07 \x01(\t\x12\x10\n\x08\x66ullplot\x18\x08 \x01(\t\x12\x11\n\tcountries\x18\t \x03(\t\x12\x10\n\x08released\x18\n \x01(\t\x12\x11\n\tdirectors\x18\x0b \x03(\t\x12\r\n\x05rated\x18\x0c \x01(\t\x12\x13\n\x0blastupdated\x18\r \x01(\t\x12\x0c\n\x04year\x18\x0e \x01(\x05\x12\x0c\n\x04type\x18\x0f \x01(\t\"\x87\x01\n\x0eRequestPayload\x12\x11\n\toperation\x18\x01 \x01(\t\x12\x10\n\x08movie_id\x18\x02 \x01(\t\x12!\n\nmovie_data\x18\x03 \x01(\x0b\x32\r.movies.Movie\x12\x14\n\x0c\x66ilter_actor\x18\x04 \x01(\t\x12\x17\n\x0f\x66ilter_category\x18\x05 \x01(\t\"V\n\x0fResponsePayload\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x1b\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\r.movies.Movieb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movies_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MOVIE._serialized_start=25
  _MOVIE._serialized_end=287
  _REQUESTPAYLOAD._serialized_start=290
  _REQUESTPAYLOAD._serialized_end=425
  _RESPONSEPAYLOAD._serialized_start=427
  _RESPONSEPAYLOAD._serialized_end=513
# @@protoc_insertion_point(module_scope)
