# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import movies_pb2 as proto_dot_movies__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/movies_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MovieServiceStub(object):
    """para gerar arquivos pb2 foi usado o comando abaixo
    python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. proto/movies.proto

    mapeia metodos remotos que server expoe
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMovie = channel.unary_unary(
                '/movies.MovieService/CreateMovie',
                request_serializer=proto_dot_movies__pb2.CreateMovieRequest.SerializeToString,
                response_deserializer=proto_dot_movies__pb2.MovieResponse.FromString,
                _registered_method=True)
        self.UpdateMovie = channel.unary_unary(
                '/movies.MovieService/UpdateMovie',
                request_serializer=proto_dot_movies__pb2.UpdateMovieRequest.SerializeToString,
                response_deserializer=proto_dot_movies__pb2.MovieResponse.FromString,
                _registered_method=True)
        self.DeleteMovie = channel.unary_unary(
                '/movies.MovieService/DeleteMovie',
                request_serializer=proto_dot_movies__pb2.MovieIdRequest.SerializeToString,
                response_deserializer=proto_dot_movies__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ReadMovie = channel.unary_unary(
                '/movies.MovieService/ReadMovie',
                request_serializer=proto_dot_movies__pb2.MovieIdRequest.SerializeToString,
                response_deserializer=proto_dot_movies__pb2.MovieResponse.FromString,
                _registered_method=True)
        self.ListMoviesByActor = channel.unary_unary(
                '/movies.MovieService/ListMoviesByActor',
                request_serializer=proto_dot_movies__pb2.ActorRequest.SerializeToString,
                response_deserializer=proto_dot_movies__pb2.MovieListResponse.FromString,
                _registered_method=True)
        self.ListMoviesByCategory = channel.unary_unary(
                '/movies.MovieService/ListMoviesByCategory',
                request_serializer=proto_dot_movies__pb2.CategoryRequest.SerializeToString,
                response_deserializer=proto_dot_movies__pb2.MovieListResponse.FromString,
                _registered_method=True)


class MovieServiceServicer(object):
    """para gerar arquivos pb2 foi usado o comando abaixo
    python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. proto/movies.proto

    mapeia metodos remotos que server expoe
    """

    def CreateMovie(self, request, context):
        """operacoes de mutacao
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadMovie(self, request, context):
        """operacoes de leitura
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMoviesByActor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMoviesByCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MovieServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMovie,
                    request_deserializer=proto_dot_movies__pb2.CreateMovieRequest.FromString,
                    response_serializer=proto_dot_movies__pb2.MovieResponse.SerializeToString,
            ),
            'UpdateMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMovie,
                    request_deserializer=proto_dot_movies__pb2.UpdateMovieRequest.FromString,
                    response_serializer=proto_dot_movies__pb2.MovieResponse.SerializeToString,
            ),
            'DeleteMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMovie,
                    request_deserializer=proto_dot_movies__pb2.MovieIdRequest.FromString,
                    response_serializer=proto_dot_movies__pb2.DeleteResponse.SerializeToString,
            ),
            'ReadMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadMovie,
                    request_deserializer=proto_dot_movies__pb2.MovieIdRequest.FromString,
                    response_serializer=proto_dot_movies__pb2.MovieResponse.SerializeToString,
            ),
            'ListMoviesByActor': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMoviesByActor,
                    request_deserializer=proto_dot_movies__pb2.ActorRequest.FromString,
                    response_serializer=proto_dot_movies__pb2.MovieListResponse.SerializeToString,
            ),
            'ListMoviesByCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMoviesByCategory,
                    request_deserializer=proto_dot_movies__pb2.CategoryRequest.FromString,
                    response_serializer=proto_dot_movies__pb2.MovieListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'movies.MovieService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('movies.MovieService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MovieService(object):
    """para gerar arquivos pb2 foi usado o comando abaixo
    python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. proto/movies.proto

    mapeia metodos remotos que server expoe
    """

    @staticmethod
    def CreateMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movies.MovieService/CreateMovie',
            proto_dot_movies__pb2.CreateMovieRequest.SerializeToString,
            proto_dot_movies__pb2.MovieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movies.MovieService/UpdateMovie',
            proto_dot_movies__pb2.UpdateMovieRequest.SerializeToString,
            proto_dot_movies__pb2.MovieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movies.MovieService/DeleteMovie',
            proto_dot_movies__pb2.MovieIdRequest.SerializeToString,
            proto_dot_movies__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movies.MovieService/ReadMovie',
            proto_dot_movies__pb2.MovieIdRequest.SerializeToString,
            proto_dot_movies__pb2.MovieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMoviesByActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movies.MovieService/ListMoviesByActor',
            proto_dot_movies__pb2.ActorRequest.SerializeToString,
            proto_dot_movies__pb2.MovieListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMoviesByCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movies.MovieService/ListMoviesByCategory',
            proto_dot_movies__pb2.CategoryRequest.SerializeToString,
            proto_dot_movies__pb2.MovieListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
